project:
  type: website
  output-dir: _site

website:
  title: "Carter King"
  favicon: images/favicon.png
  navbar:
    background: primary
    left:
      - href: about.qmd
        text: Home
      - href: problems.qmd
        text: Problems
      - href: projects/project-1.qmd
        text: Baby Game

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
